// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title  AffiliateRewards
 * @notice On-chain referral tracking and affiliate reward distribution.
 *
 *         Architecture:
 *           • Any address can register as an affiliate (optionally with a
 *             human-readable code).
 *           • Referrers earn a configurable % of fees generated by their
 *             referred users across integrated protocol actions.
 *           • Multi-level support: up to 3 levels of referral hierarchy.
 *           • DWT tier holders earn higher commission rates.
 *           • Rewards accumulate on-chain; affiliates pull-claim at any time.
 *           • Protocol hooks: other Layer-9 contracts call `recordActivity()`
 *             to credit referrer commissions.
 *
 *         Commission model (configurable per tier level):
 *           Level 1 (direct referrer):   5%  default
 *           Level 2 (referrer's referrer): 2%  default
 *           Level 3 (grandparent):         1%  default
 *
 *         DWT tier multipliers (via NFTMembership):
 *           Bronze  →  1.0 ×  base commission
 *           Silver  →  1.2 ×
 *           Gold    →  1.5 ×
 *           Platinum → 2.0 ×
 */

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "./NFTMembership.sol";
import "../SecurityGated.sol";

contract AffiliateRewards is ReentrancyGuard, Pausable, AccessControl, SecurityGated {
    using SafeERC20 for IERC20;

    // ── Roles ─────────────────────────────────────────────────────────────────
    bytes32 public constant ADMIN_ROLE    = keccak256("ADMIN_ROLE");
    bytes32 public constant GOVERNOR_ROLE = keccak256("GOVERNOR_ROLE");
    bytes32 public constant GUARDIAN_ROLE = keccak256("GUARDIAN_ROLE");
    
    bytes32 public constant LAYER_ID      = keccak256("LAYER_9_SETTLEMENT");

    // ── Errors ────────────────────────────────────────────────────────────────
    error AlreadyRegistered();
    error NotRegistered();
    error CodeTaken();
    error SelfReferral();
    error ZeroAddress();
    error ZeroAmount();
    error InvalidLevel();
    error NothingToClaim();
    error NotWhitelistedCaller();
    error InvalidCode();

    // ── Action IDs for Rate Limiting ─────────────────────────────────────────
    bytes32 public constant ACTION_CLAIM_REWARD = keccak256("ACTION_CLAIM_REWARD");

    // ── Events ────────────────────────────────────────────────────────────────
    event AffiliateRegistered(address indexed affiliate, address indexed referrer, bytes32 code);
    event ActivityRecorded(
        address indexed referee,
        address indexed token,
        uint256 volume,
        uint256 level1Reward,
        uint256 level2Reward,
        uint256 level3Reward
    );
    event RewardClaimed(address indexed affiliate, address indexed token, uint256 amount);
    event CommissionUpdated(uint8 level, uint256 bps);
    event TierMultiplierUpdated(uint8 tier, uint256 multiplierBps);
    event CallerWhitelisted(address indexed caller, bool status);
    event RewardTokenAdded(address indexed token);

    // ── Constants ─────────────────────────────────────────────────────────────
    uint256 public constant BPS_DENOM    = 10_000;
    uint8   public constant MAX_LEVELS   = 3;
    uint256 public constant MAX_COMMISSION_BPS = 2000; // 20% max per level total

    // ── Structs ───────────────────────────────────────────────────────────────
    struct AffiliateInfo {
        address referrer;      // direct upline (level-1 beneficiary)
        bytes32 code;          // human-readable code hash
        uint256 totalVolume;   // lifetime volume referred
        uint256 totalReferrals;
        uint256 registeredAt;
        bool    active;
    }

    // ── State ─────────────────────────────────────────────────────────────────
    NFTMembership public immutable membershipNFT;

    /// @dev Level → commission in BPS (1 = 0.01%)
    mapping(uint8 => uint256) public commissionBPS;

    /// @dev NFT tier → multiplier in BPS (10000 = 1.0x)
    mapping(uint8 => uint256) public tierMultiplierBPS;

    /// @dev Affiliate info per address
    mapping(address => AffiliateInfo) public affiliates;

    /// @dev Referral code (bytes32 hash) → affiliate address
    mapping(bytes32 => address) public codeToAffiliate;

    /// @dev Referee → their referrer (first-time registration)
    mapping(address => address) public referredBy;

    /// @dev affiliate → token → pending reward balance
    mapping(address => mapping(address => uint256)) public pendingRewards;

    /// @dev affiliate → token → lifetime claimed
    mapping(address => mapping(address => uint256)) public lifetimeClaimed;

    /// @dev Whitelisted protocol contracts that can call recordActivity()
    mapping(address => bool) public whitelistedCallers;

    /// @dev Supported reward tokens
    address[] public rewardTokens;
    mapping(address => bool) public isRewardToken;

    // ── Constructor ───────────────────────────────────────────────────────────
    constructor(
        address _membershipNFT, 
        address _admin,
        address _governor,
        address _guardian,
        address _securityController,
        address _registry,
        address _access,
        address _time,
        address _state,
        address _rate,
        address _verify
    ) SecurityGated(_securityController) {
        if (_membershipNFT == address(0)) revert ZeroAddress();
        membershipNFT = NFTMembership(payable(_membershipNFT));

        // Default commissions: L1=5%, L2=2%, L3=1%
        commissionBPS[1] = 500;
        commissionBPS[2] = 200;
        commissionBPS[3] = 100;

        // Default tier multipliers
        tierMultiplierBPS[0] = 10_000; // Bronze  1.0×
        tierMultiplierBPS[1] = 12_000; // Silver  1.2×
        tierMultiplierBPS[2] = 15_000; // Gold    1.5×
        tierMultiplierBPS[3] = 20_000; // Platinum 2.0×

        _grantRole(DEFAULT_ADMIN_ROLE, _admin);
        _grantRole(ADMIN_ROLE,         _admin);
        _grantRole(GOVERNOR_ROLE,      _governor);
        _grantRole(GUARDIAN_ROLE,      _guardian);

        _initSecurityModules(_registry, _access, _time, _state, _rate, _verify);
    }

    // ── Admin ─────────────────────────────────────────────────────────────────

    function setCommission(uint8 level, uint256 bps, bytes32 hash, bytes calldata signature) 
        external 
        onlyRole(GOVERNOR_ROLE) 
        whenProtocolNotPaused 
        withSignature(hash, signature)
    {
        if (level == 0 || level > MAX_LEVELS) revert InvalidLevel();
        commissionBPS[level] = bps;
        emit CommissionUpdated(level, bps);
    }

    function setTierMultiplier(uint8 tier, uint256 bps, bytes32 hash, bytes calldata signature) 
        external 
        onlyRole(GOVERNOR_ROLE) 
        whenProtocolNotPaused 
        withSignature(hash, signature)
    {
        tierMultiplierBPS[tier] = bps;
        emit TierMultiplierUpdated(tier, bps);
    }

    function setWhitelistedCaller(address caller, bool status, bytes32 hash, bytes calldata signature) 
        external 
        onlyRole(ADMIN_ROLE) 
        whenProtocolNotPaused 
        withSignature(hash, signature)
    {
        whitelistedCallers[caller] = status;
        emit CallerWhitelisted(caller, status);
    }

    function addRewardToken(address token, bytes32 hash, bytes calldata signature) 
        external 
        onlyRole(GOVERNOR_ROLE) 
        whenProtocolNotPaused 
        withSignature(hash, signature)
    {
        if (token == address(0)) revert ZeroAddress();
        if (!isRewardToken[token]) {
            isRewardToken[token] = true;
            rewardTokens.push(token);
            emit RewardTokenAdded(token);
        }
    }

    function pause()   external onlyRole(GUARDIAN_ROLE) { _pause(); }
    function unpause() external onlyRole(GOVERNOR_ROLE) { _unpause(); }

    // ── Registration ──────────────────────────────────────────────────────────

    /**
     * @notice Register as an affiliate.
     * @param referrer    Upline affiliate (address(0) if top-level)
     * @param codeString  Desired human-readable referral code (e.g. "ALICE2025")
     */
    function register(address referrer, string calldata codeString)
        external
        whenNotPaused
        whenProtocolNotPaused
        withStateGuard(LAYER_ID)
    {
        if (affiliates[msg.sender].active) revert AlreadyRegistered();
        if (referrer == msg.sender)        revert SelfReferral();

        bytes32 code = bytes32(0);
        if (bytes(codeString).length > 0) {
            code = keccak256(bytes(codeString));
            if (codeToAffiliate[code] != address(0)) revert CodeTaken();
            codeToAffiliate[code] = msg.sender;
        }

        // Validate referrer is registered (or zero)
        if (referrer != address(0) && !affiliates[referrer].active)
            revert NotRegistered();

        affiliates[msg.sender] = AffiliateInfo({
            referrer:       referrer,
            code:           code,
            totalVolume:    0,
            totalReferrals: 0,
            registeredAt:   block.timestamp,
            active:         true
        });

        referredBy[msg.sender] = referrer;

        // Credit referrer's referral count
        if (referrer != address(0)) {
            affiliates[referrer].totalReferrals++;
        }

        emit AffiliateRegistered(msg.sender, referrer, code);
    }

    /**
     * @notice Register using a referral code string (convenience wrapper).
     * @param codeString   Referrer's code
     * @param myCodeString Desired code for this registrant (empty = none)
     */
    function registerWithCode(string calldata codeString, string calldata myCodeString)
        external
        whenNotPaused
        whenProtocolNotPaused
    {
        bytes32 code = keccak256(bytes(codeString));
        address referrer = codeToAffiliate[code];
        if (referrer == address(0)) revert InvalidCode();
        // Delegate to main registration
        if (affiliates[msg.sender].active) revert AlreadyRegistered();
        if (referrer == msg.sender) revert SelfReferral();

        bytes32 myCode = bytes32(0);
        if (bytes(myCodeString).length > 0) {
            myCode = keccak256(bytes(myCodeString));
            if (codeToAffiliate[myCode] != address(0)) revert CodeTaken();
            codeToAffiliate[myCode] = msg.sender;
        }

        affiliates[msg.sender] = AffiliateInfo({
            referrer:       referrer,
            code:           myCode,
            totalVolume:    0,
            totalReferrals: 0,
            registeredAt:   block.timestamp,
            active:         true
        });

        referredBy[msg.sender] = referrer;
        affiliates[referrer].totalReferrals++;

        emit AffiliateRegistered(msg.sender, referrer, myCode);
    }

    // ── Activity recording ────────────────────────────────────────────────────

    /**
     * @notice Record a revenue-generating activity by a referee and distribute
     *         commissions up the referral chain.
     *
     *         Called by whitelisted protocol contracts (LendingMarket, Launchpad…)
     *         AFTER pulling the fee from the user into this contract.
     *
     * @param referee  The user who performed the action
     * @param token    The fee token transferred
     * @param feeAmount The total fee collected (already held by this contract)
     */
    function recordActivity(
        address referee,
        address token,
        uint256 feeAmount
    ) external whenNotPaused whenProtocolNotPaused withStateGuard(LAYER_ID) {
        if (!whitelistedCallers[msg.sender]) revert NotWhitelistedCaller();
        if (!isRewardToken[token])           revert ZeroAddress(); // unsupported token
        if (feeAmount == 0)                  revert ZeroAmount();

        affiliates[referee].totalVolume += feeAmount;

        // Walk up 3 levels
        address current  = referredBy[referee];
        uint256 l1Reward;
        uint256 l2Reward;
        uint256 l3Reward;

        for (uint8 level = 1; level <= MAX_LEVELS && current != address(0); level++) {
            uint256 bps      = commissionBPS[level];
            if (bps == 0) { current = affiliates[current].referrer; continue; }

            // Apply tier multiplier
            uint8   tier     = _activeTier(current);
            uint256 multBPS  = tierMultiplierBPS[tier];
            uint256 reward   = (feeAmount * bps * multBPS) / (BPS_DENOM * BPS_DENOM);

            pendingRewards[current][token] += reward;

            if (level == 1) l1Reward = reward;
            else if (level == 2) l2Reward = reward;
            else l3Reward = reward;

            current = affiliates[current].referrer;
        }

        emit ActivityRecorded(referee, token, feeAmount, l1Reward, l2Reward, l3Reward);
    }

    /**
     * @notice Convenience: record + pull fee from the calling contract.
     *         The calling contract must approve this contract first.
     */
    function recordAndPull(
        address referee,
        address token,
        uint256 feeAmount
    ) external whenNotPaused whenProtocolNotPaused withStateGuard(LAYER_ID) {
        if (!whitelistedCallers[msg.sender]) revert NotWhitelistedCaller();
        IERC20(token).safeTransferFrom(msg.sender, address(this), feeAmount);
        // Re-enter via internal logic (no reentrancy risk here, same tx)
        _distributeCommissions(referee, token, feeAmount);
    }

    function _distributeCommissions(address referee, address token, uint256 feeAmount) internal {
        if (!isRewardToken[token]) revert ZeroAddress();
        affiliates[referee].totalVolume += feeAmount;

        address current = referredBy[referee];
        uint256 l1; uint256 l2; uint256 l3;
        for (uint8 level = 1; level <= MAX_LEVELS && current != address(0); level++) {
            uint256 bps = commissionBPS[level];
            if (bps == 0) { current = affiliates[current].referrer; continue; }
            uint8   tier    = _activeTier(current);
            uint256 multBPS = tierMultiplierBPS[tier];
            uint256 reward  = (feeAmount * bps * multBPS) / (BPS_DENOM * BPS_DENOM);
            pendingRewards[current][token] += reward;
            if (level == 1) l1 = reward;
            else if (level == 2) l2 = reward;
            else l3 = reward;
            current = affiliates[current].referrer;
        }
        emit ActivityRecorded(referee, token, feeAmount, l1, l2, l3);
    }

    // ── Claiming ──────────────────────────────────────────────────────────────

    /**
     * @notice Claim accumulated rewards for a single token.
     * @param token Reward token to claim
     */
    function claim(address token) 
        external 
        nonReentrant 
        whenNotPaused 
        whenProtocolNotPaused 
        withStateGuard(LAYER_ID)
        withRateLimit(ACTION_CLAIM_REWARD, pendingRewards[msg.sender][token])
    {
        uint256 amount = pendingRewards[msg.sender][token];
        if (amount == 0) revert NothingToClaim();

        pendingRewards[msg.sender][token]  = 0;
        lifetimeClaimed[msg.sender][token] += amount;

        IERC20(token).safeTransfer(msg.sender, amount);
        emit RewardClaimed(msg.sender, token, amount);
    }

    /**
     * @notice Claim rewards for all registered reward tokens in one tx.
     */
    function claimAll() 
        external 
        nonReentrant 
        whenNotPaused 
        whenProtocolNotPaused 
        withStateGuard(LAYER_ID)
    {
        for (uint256 i; i < rewardTokens.length; ++i) {
            address token  = rewardTokens[i];
            uint256 amount = pendingRewards[msg.sender][token];
            if (amount == 0) continue;
            pendingRewards[msg.sender][token]  = 0;
            lifetimeClaimed[msg.sender][token] += amount;
            IERC20(token).safeTransfer(msg.sender, amount);
            emit RewardClaimed(msg.sender, token, amount);
        }
    }

    // ── Referral tree traversal ───────────────────────────────────────────────

    /**
     * @notice Returns the referral chain for an address (up to MAX_LEVELS).
     */
    function getReferralChain(address user)
        external
        view
        returns (address[3] memory chain)
    {
        address current = referredBy[user];
        for (uint8 i; i < MAX_LEVELS && current != address(0); ++i) {
            chain[i] = current;
            current  = affiliates[current].referrer;
        }
    }

    /**
     * @notice Returns all pending rewards across all reward tokens for an affiliate.
     */
    function allPendingRewards(address affiliate)
        external
        view
        returns (address[] memory tokens, uint256[] memory amounts)
    {
        tokens  = rewardTokens;
        amounts = new uint256[](rewardTokens.length);
        for (uint256 i; i < rewardTokens.length; ++i) {
            amounts[i] = pendingRewards[affiliate][rewardTokens[i]];
        }
    }

    /**
     * @notice Resolve a referral code string to its affiliate address.
     */
    function resolveCode(string calldata codeString) external view returns (address) {
        return codeToAffiliate[keccak256(bytes(codeString))];
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    function _activeTier(address user) internal view returns (uint8) {
        uint8 tier = membershipNFT.activeTier(user);
        return tier == type(uint8).max ? 0 : tier;
    }

    // ── Emergency rescue ─────────────────────────────────────────────────────

    /**
     * @notice Rescue tokens accidentally sent to this contract (non-reward tokens).
     */
    /**
     * @notice Rescue tokens accidentally sent to this contract. Requires Committee Multi-Sig.
     */
    function rescueToken(address token, address to, uint256 amount, bytes32 hash, bytes calldata signature) 
        external 
        onlyRole(ADMIN_ROLE) 
        whenProtocolNotPaused 
        withSignature(hash, signature)
    {
        IERC20(token).safeTransfer(to, amount);
    }
}
