#!/bin/bash

# Layer 8 - Faucet Funding Guide
# This script helps you get testnet ETH for multi-chain deployment

DEPLOYER_ADDRESS="0x4C0B7314441dfE8E61267C0d87Fc1A657611dCf5"

echo "════════════════════════════════════════════════════"
echo "  Layer 8 - Faucet Funding Guide"
echo "════════════════════════════════════════════════════"
echo ""
echo "Deployer Address: $DEPLOYER_ADDRESS"
echo ""

echo "📊 Current Balance Check:"
echo "──────────────────────────────────────────────────"

# Check Base Sepolia (should have funds)
echo ""
echo "1. Base Sepolia (Chain ID: 84532)"
echo "   Status: ✅ Already funded (deployment successful)"
echo "   Check: cast balance $DEPLOYER_ADDRESS --rpc-url https://sepolia.base.org"

# Check Arbitrum Sepolia
echo ""
echo "2. Arbitrum Sepolia (Chain ID: 421614)"
echo "   Status: ❌ Needs funding"
echo "   Check: cast balance $DEPLOYER_ADDRESS --rpc-url https://sepolia-rollup.arbitrum.io/rpc"
echo ""
echo "   🚰 Get Faucet From:"
echo "   - https://faucet.quicknode.com/arbitrum/sepolia"
echo "   - https://www.alchemy.com/faucets/arbitrum-sepolia"
echo "   - https://cloud.google.com/application/web3/faucet/ethereum/arbitrum-sepolia"

# Check Polygon Amoy
echo ""
echo "3. Polygon Amoy (Chain ID: 80002)"
echo "   Status: ❌ Needs funding"
echo "   Check: cast balance $DEPLOYER_ADDRESS --rpc-url https://rpc-amoy.polygon.technology"
echo ""
echo "   🚰 Get Faucet From:"
echo "   - https://faucet.polygon.technology/"
echo "   - https://www.alchemy.com/faucets/polygon-amoy"
echo "   - https://cloud.google.com/application/web3/faucet/ethereum/polygon-amoy"

echo ""
echo "════════════════════════════════════════════════════"
echo "  Quick Faucet Commands (if you have cast/Foundry)"
echo "════════════════════════════════════════════════════"
echo ""
echo "# Check current balances:"
echo "cast balance $DEPLOYER_ADDRESS --rpc-url https://sepolia-rollup.arbitrum.io/rpc"
echo "cast balance $DEPLOYER_ADDRESS --rpc-url https://rpc-amoy.polygon.technology"
echo ""

echo "════════════════════════════════════════════════════"
echo "  Required Amounts"
echo "════════════════════════════════════════════════════"
echo ""
echo "Per Chain:"
echo "  - Deployment gas: ~0.01 ETH"
echo "  - Relayer stake (if testing): 1 ETH"
echo "  - Buffer for testing: 0.1 ETH"
echo "  ─────────────────────────────"
echo "  Recommended: 1.5 ETH per chain"
echo ""
echo "Total for 2 chains: ~3 ETH"
echo ""

echo "════════════════════════════════════════════════════"
echo "  After Getting Funds"
echo "════════════════════════════════════════════════════"
echo ""
echo "Run these commands:"
echo ""
echo "1. Deploy to Arbitrum Sepolia:"
echo "   npx hardhat run scripts/deploy-layer8.cjs --network arbitrumSepolia"
echo ""
echo "2. Deploy to Polygon Amoy:"
echo "   npx hardhat run scripts/deploy-layer8.cjs --network polygonAmoy"
echo ""
echo "3. Verify balances:"
echo "   npx hardhat run scripts/verify-layer8-deployment.cjs --network arbitrumSepolia"
echo "   npx hardhat run scripts/verify-layer8-deployment.cjs --network polygonAmoy"
echo ""

echo "════════════════════════════════════════════════════"
echo "  Manual Faucet Steps"
echo "════════════════════════════════════════════════════"
echo ""
echo "Step 1: Visit faucet websites listed above"
echo "Step 2: Enter your deployer address: $DEPLOYER_ADDRESS"
echo "Step 3: Complete any CAPTCHA or social tasks"
echo "Step 4: Wait for funds to arrive (usually 1-5 minutes)"
echo "Step 5: Verify balance and proceed with deployment"
echo ""

echo "════════════════════════════════════════════════════"
echo ""
